apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webservice
  template:
    metadata:
      labels:
        app: python-webservice
    spec:
      containers:
      - name: python-webservice
        image: ghcr.io/clickandobey/python-dockerized-webservice:1.0.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: python-webservice
  namespace: apps
spec:
  selector:
    app: python-webservice
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP